; generated by Component: ARM Compiler 5.06 update 4 (build 422) Tool: ArmCC [4d3604]
; commandline ArmCC [--c99 --split_sections --debug -c -S -o.\objects\stm32f10x_it.s --depend=.\objects\stm32f10x_it.d --cpu=Cortex-M3 --apcs=interwork -O0 --diag_suppress=9931 -I..\Application -I..\STDevice\Include -I..\STDevice\USB_Driver\inc -I..\STDevice\StdPeriph_Driver\inc -I..\STDevice\StdPeriph_Driver\templates -I..\RTOS\include -I..\RTOS\libcpu -I..\RTOS\src -I.\RTE\_BadUSB -Id:\Keil_v5\ARM\PACK\ARM\CMSIS\5.0.1\CMSIS\Include -Id:\Keil_v5\ARM\PACK\Keil\STM32F1xx_DFP\2.1.0\Device\Include -D__UVISION_VERSION=523 -D_RTE_ -DSTM32F10X_HD -DUSE_STDPERIPH_DRIVER -DSTM32F10X_HD --omf_browse=.\objects\stm32f10x_it.crf ..\STDevice\StdPeriph_Driver\templates\stm32f10x_it.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.BusFault_Handler||, CODE, READONLY, ALIGN=1

BusFault_Handler PROC
        NOP      
|L0.2|
        B        |L0.2|
        ENDP


        AREA ||i.DebugMon_Handler||, CODE, READONLY, ALIGN=1

DebugMon_Handler PROC
        BX       lr
        ENDP


        AREA ||i.HardFault_Handler||, CODE, READONLY, ALIGN=1

HardFault_Handler PROC
        NOP      
|L2.2|
        B        |L2.2|
        ENDP


        AREA ||i.MemManage_Handler||, CODE, READONLY, ALIGN=1

MemManage_Handler PROC
        NOP      
|L3.2|
        B        |L3.2|
        ENDP


        AREA ||i.NMI_Handler||, CODE, READONLY, ALIGN=1

NMI_Handler PROC
        BX       lr
        ENDP


        AREA ||i.PendSV_Handler||, CODE, READONLY, ALIGN=1

PendSV_Handler PROC
        BX       lr
        ENDP


        AREA ||i.SVC_Handler||, CODE, READONLY, ALIGN=1

SVC_Handler PROC
        BX       lr
        ENDP


        AREA ||i.SysTick_Handler||, CODE, READONLY, ALIGN=1

SysTick_Handler PROC
        BX       lr
        ENDP


        AREA ||i.UsageFault_Handler||, CODE, READONLY, ALIGN=1

UsageFault_Handler PROC
        NOP      
|L8.2|
        B        |L8.2|
        ENDP


        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "..\\STDevice\\StdPeriph_Driver\\templates\\stm32f10x_it.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___14_stm32f10x_it_c_bb8ca80c____REV16|
#line 447 "d:\\Keil_v5\\ARM\\PACK\\ARM\\CMSIS\\5.0.1\\CMSIS\\Include\\cmsis_armcc.h"
|__asm___14_stm32f10x_it_c_bb8ca80c____REV16| PROC
#line 448

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___14_stm32f10x_it_c_bb8ca80c____REVSH|
#line 462
|__asm___14_stm32f10x_it_c_bb8ca80c____REVSH| PROC
#line 463

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___14_stm32f10x_it_c_bb8ca80c____RRX|
#line 649
|__asm___14_stm32f10x_it_c_bb8ca80c____RRX| PROC
#line 650

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT BusFault_Handler [CODE]
        EXPORT DebugMon_Handler [CODE]
        EXPORT HardFault_Handler [CODE]
        EXPORT MemManage_Handler [CODE]
        EXPORT NMI_Handler [CODE]
        EXPORT PendSV_Handler [CODE]
        EXPORT SVC_Handler [CODE]
        EXPORT SysTick_Handler [CODE]
        EXPORT UsageFault_Handler [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
